services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    environment:
      POSTGRES_USER: $(POSTGRES_USER)
      POSTGRES_PASSWORD: $(POSTGRES_PASSWORD)
      POSTGRES_DB: $(POSTGRES_DB)
    ports:
      - "$(POSTGRES_PORT):5432"
    volumes:
        - pgdata:/var/lib/postgresql/data
        - ./Docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $(POSTGRES_USER) -d $(POSTGRES_DB)"]
      interval: 10s
      timeout: 5s
      retries: 5
  
 rabbbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: $(RABBITMQ_USER)
      RABBITMQ_DEFAULT_PASS: $(RABBITMQ_PASSWORD)
    ports:
      - "$(RABBITMQ_PORT):5672"
      - "$(RABBITMQ_MANAGEMENT_PORT):15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

 core-api:
    build: ./Backend/App.Core
    container_name: core-api
    environment:
      DATABASE_URL: $(DATABASE_URL)
      RABBITMQ_URL: $(RABBITMQ_URL)
      CORS_AllowOrigin: $(WEB_ORIGIN)
      
#      PORT: $(CORE_API_PORT)
#      OTHER_ENV_VARS: $(OTHER_ENV_VARS)
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:$(CORE_API_PORT)/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      
      
 ai-worker:
    build: ./Ai-worker
    container_name: ai-worker
    environment:
      DATABASE_URL: $(DATABASE_URL)
      RABBITMQ_URL: $(RABBITMQ_URL)
      OPENAI_API_KEY: $(OPENAI_API_KEY)
      WEB_ORIGIN: $(WEB_ORIGIN)
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      rabbbitmq:
        condition: service_healthy  
        
  react-app:
    build: ./Frontend/react-app
    container_name: react-app
    environment:
      REACT_APP_API_URL: $(REACT_APP_API_URL)
      AI_SERVICE_URL: $(AI_SERVICE_URL)
    ports:
      - "5173:5173"
    depends_on:
      core-api:
        condition: service_healthy
      ai-worker:
        condition: service_healthy
    
volumes:    
    pgdata:
        driver: local
        